apiVersion: v1
kind: Service
metadata:
  name: tdd-mockmvc-api
  namespace: neiton
spec:
  type: NodePort
  selector:
    app: tdd-mockmvc-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080